name:                Weatherapp
version:             0.1.0.0
github:              "githubuser/Weatherapp"
license:             BSD3
author:              "Sankar Muthusangu"
maintainer:          "sankaraj06@gmail.com"
copyright:           "2022 Sankar Muthusangu"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/Weatherapp#readme>

dependencies:
- base >= 4.7 && < 5
- ini
- text
- transformers
- aeson
- HTTP
- bytestring
- http-conduit
- HaskellNet
- HaskellNet-SSL
- mime-mail

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  Weatherapp-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Weatherapp

tests:
  Weatherapp-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Weatherapp
